apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: monitoring
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    run: app1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    run: app1
  name: app1
spec:
  selector:
    matchLabels:
      run: app1
  template:
    metadata:
      labels:
        run: app1
    spec:
      containers:
        - name: app1
          image: thanhmanci/testt:app1_v_2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: app_3
              value: "http://app3.monitoring.svc:5003"
            - name: app_1
              value: "http://app3.monitoring.svc:5001"
            - name: rabbit_host
              value: "rabbitmq.infrastructure.svc"
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: monitoring
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    run: app2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    run: app2
  name: app2
spec:
  selector:
    matchLabels:
      run: app2
  template:
    metadata:
      labels:
        run: app2
    spec:
      containers:
        - name: app2
          image: thanhmanci/testt:app2_v_2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: app_3
              value: "http://app3.monitoring.svc:5003"
            - name: app_1
              value: "http://app3.monitoring.svc:5001"
            - name: rabbit_host
              value: "rabbitmq.infrastructure.svc"
---
apiVersion: v1
kind: Service
metadata:
  name: app3
  namespace: monitoring
spec:
  ports:
    - port: 5003
      protocol: TCP
      targetPort: 5003
  selector:
    run: app3
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    run: app3
  name: app3
spec:
  selector:
    matchLabels:
      run: app3
  template:
    metadata:
      labels:
        run: app3
    spec:
      containers:
        - name: app3
          image: thanhmanci/testt:app3_v_2
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5003"
            - name: app_3
              value: "http://app3.monitoring.svc:5003"
            - name: app_1
              value: "http://app3.monitoring.svc:5001"
            - name: rabbit_host
              value: "rabbitmq.infrastructure.svc"
---
apiVersion: v1
kind: Service
metadata:
  name: app4
  namespace: monitoring
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    run: app4
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    run: app4
  name: app4
spec:
  selector:
    matchLabels:
      run: app4
  template:
    metadata:
      labels:
        run: app4
    spec:
      containers:
        - name: app4
          image: thanhmanci/testt:app4_v_2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: app_3
              value: "http://app3.monitoring.svc:5003"
            - name: app_1
              value: "http://app3.monitoring.svc:5001"
            - name: rabbit_host
              value: "rabbitmq.infrastructure.svc"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: monitoring
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    run: redis
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  labels:
    run: redis
  name: redis
spec:
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.4
          command: ["redis-server"]
          env:
          - name: MASTER
            value: "true"
          ports:
            - containerPort: 6379

